import React, { useState } from 'react';
import {
  Sparkles,
  FileText,
  RefreshCw,
  Share2,
  CheckCircle2,
  Cpu,
  Layers,
  ShieldAlert,
} from 'lucide-react';
import { SituationBrief } from '../../types/disaster';
import { disastraApi } from '../../services/api';

interface AISituationBriefProps {
  initialBrief: SituationBrief;
}

export const AISituationBrief: React.FC<AISituationBriefProps> = ({ initialBrief }) => {
  const [brief, setBrief] = useState<SituationBrief>(initialBrief);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [aiStatus, setAiStatus] = useState<'DEMO / PREVIEW' | 'GENERATING' | 'LIVE — GEMINI' | 'AI UNAVAILABLE' | 'AWAITING ANALYSIS'>(
    initialBrief.headline === 'AWAITING ANALYSIS' ? 'AWAITING ANALYSIS' : 'DEMO / PREVIEW'
  );

  const handleRefreshBrief = async () => {
    setIsRefreshing(true);
    setAiStatus('GENERATING');
    try {
      const refreshed = await disastraApi.getSituationBrief({ forceRefresh: true });
      setBrief({
        ...refreshed,
        generatedAt: `Today, ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })} IST (Fresh Ingestion)`,
      });
      setAiStatus('LIVE — GEMINI');
    } catch (err) {
      console.error('Failed to refresh brief', err);
      setAiStatus('AI UNAVAILABLE');
      setBrief({
        id: 'error-brief',
        headline: 'AI SITUATION REPORT UNAVAILABLE',
        executiveSummary: err instanceof Error ? err.message : 'The Generative Intelligence Layer is currently offline or unreachable.',
        keyThreats: ['Data synthesis pipeline offline'],
        recommendedActions: ['Ensure Flood Detection is executed first to populate analysis context.', 'Check backend connectivity and configuration.'],
        generatedAt: `Today, ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })} IST`,
        generatedBy: 'Fallback System',
        modelEngine: 'None',
        dataSources: [],
        confidenceScorePct: 0,
      });
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleCopyText = () => {
    const text = `${brief.headline}\n\n${brief.executiveSummary}\n\nKey Threats:\n${brief.keyThreats.map((t) => `- ${t}`).join('\n')}\n\nRecommended Actions:\n${brief.recommendedActions.map((a) => `- ${a}`).join('\n')}\n\nGenerated by ${brief.generatedBy}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="ai-situation-brief-section" className="w-full border-b border-slate-200 bg-white py-10">
      <div className="mx-auto max-w-7xl px-4 sm:px-8">
        {/* Section Header */}
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between border-b border-slate-200 pb-5">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold tracking-wider text-slate-500 uppercase">
              <span>Generative Disaster Synthesis</span>
              <span aria-hidden="true">·</span>
              <span className={`font-bold ${
                aiStatus === 'LIVE — GEMINI' ? 'text-emerald-600' :
                aiStatus === 'AI UNAVAILABLE' ? 'text-rose-600' :
                aiStatus === 'GENERATING' ? 'text-amber-600 animate-pulse' :
                'text-slate-800'
              }`}>
                {aiStatus}
              </span>
            </div>
            <h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">
              AI Situation Brief
            </h2>
            <p className="mt-1 text-sm text-slate-600">
              Autonomous multi-source intelligence briefing synthesizing real-time radar passes, hydrological runoffs, and cyclogenesis trajectories.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleRefreshBrief}
              disabled={isRefreshing}
              className="inline-flex cursor-pointer items-center gap-2 rounded border border-slate-300 bg-white px-3.5 py-2 text-xs font-semibold text-slate-800 shadow-xs transition-colors hover:bg-slate-50 disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isRefreshing ? 'animate-spin' : ''}`} />
              <span>{isRefreshing ? 'Generating Synthesized Brief...' : 'Re-Synthesize Brief'}</span>
            </button>

            <button
              type="button"
              onClick={handleCopyText}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
            >
              <FileText className="h-3.5 w-3.5 text-slate-500" />
              <span>{copied ? 'Copied to Clipboard' : 'Copy Brief'}</span>
            </button>
          </div>
        </div>

        {/* Executive Briefing Card */}
        <div className="mt-8 rounded border border-slate-200 bg-slate-50/40 p-6 md:p-8">
          <div className="max-w-4xl space-y-6">
            {/* Headline */}
            <div>
              <div className="flex items-center gap-2 text-xs font-mono uppercase text-slate-500 mb-1">
                <span>INCIDENT BULLETIN</span>
                <span aria-hidden="true">·</span>
                <span className="font-bold text-rose-600">COMPOUND METEOROLOGICAL THREAT</span>
              </div>
              <h3 className="font-display text-2xl font-bold text-slate-950 sm:text-3xl leading-snug">
                {brief.headline}
              </h3>
            </div>

            {/* Executive Summary paragraph with refined editorial prose */}
            <div className="border-l-2 border-slate-900 pl-4">
              <p className="text-base text-slate-800 leading-relaxed font-normal">
                {brief.executiveSummary}
              </p>
            </div>

            {/* Two-column layout: Key Threats vs Recommended Autonomous Actions */}
            <div className="grid grid-cols-1 gap-6 pt-4 border-t border-slate-200 sm:grid-cols-2">
              {/* Key Threats */}
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-rose-800">
                  <ShieldAlert className="h-4 w-4 text-rose-600" />
                  <span>Critical Observed Threats</span>
                </div>
                <ul className="space-y-2 text-xs text-slate-700 leading-relaxed font-normal">
                  {brief.keyThreats.map((threat, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="mt-1 h-1.5 w-1.5 rounded-full bg-rose-600 shrink-0" />
                      <span>{threat}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Recommended Actions */}
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-900">
                  <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                  <span>Autonomous Response Directives</span>
                </div>
                <ul className="space-y-2 text-xs text-slate-700 leading-relaxed font-normal">
                  {brief.recommendedActions.map((action, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="mt-1 h-1.5 w-1.5 rounded-full bg-slate-900 shrink-0" />
                      <span>{action}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Attribution & Data Sources Footer (Requested in prompt) */}
            <div className="mt-6 rounded border border-slate-200 bg-white p-4 text-xs">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <div>
                  <div className="font-mono text-[10px] uppercase text-slate-400">Generated By</div>
                  <div className="font-semibold text-slate-900">{brief.generatedBy}</div>
                  <div className="font-mono text-[11px] text-slate-500">{brief.modelEngine}</div>
                </div>

                <div>
                  <div className="font-mono text-[10px] uppercase text-slate-400">Multi-Modal Ingestion Sources</div>
                  <div className="space-y-0.5 text-[11px] text-slate-700 font-medium">
                    {brief.dataSources.slice(0, 3).map((src, i) => (
                      <div key={i}>{i + 1}. {src}</div>
                    ))}
                  </div>
                </div>

                <div>
                  <div className="font-mono text-[10px] uppercase text-slate-400">Telemetry Metadata</div>
                  <div className="font-mono text-[11px] text-slate-600">
                    <div>Timestamp: {brief.generatedAt}</div>
                    <div>Confidence: <strong className="text-emerald-700">{brief.confidenceScorePct}%</strong></div>
                    <div className="text-slate-400">API: POST /api/ai/brief</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
